spring.application.name=auth-service

server.port=8081

# Registro en Discovery Server (Eureka)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/auth_service?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Circular references
spring.main.allow-circular-references=true

# JWT — misma clave que usara el api-gateway para validar
jwt.secret=mi-clave-super-secreta-proyecto-final-123456789-idat-2026
jwt.expiration=3000000

